// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1iumzSOtRXvXvfoNIlcJqHtcHZe77SeY',
    appId: '1:1018122395869:web:9aedf8e86f230d3d7d3b34',
    messagingSenderId: '1018122395869',
    projectId: 'meditechapp-86337',
    authDomain: 'meditechapp-86337.firebaseapp.com',
    storageBucket: 'meditechapp-86337.firebasestorage.app',
    measurementId: 'G-083Z6X9FEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cmC59u7_cGx8lnj3H6ADb9lHiNGbnFE',
    appId: '1:1018122395869:android:807228bddcd5d73a7d3b34',
    messagingSenderId: '1018122395869',
    projectId: 'meditechapp-86337',
    storageBucket: 'meditechapp-86337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRtNa-TAV7PiA47BUXBuqMdxkpyrUQvE',
    appId: '1:1018122395869:ios:54fca69309360a547d3b34',
    messagingSenderId: '1018122395869',
    projectId: 'meditechapp-86337',
    storageBucket: 'meditechapp-86337.firebasestorage.app',
    iosBundleId: 'com.example.meditech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRtNa-TAV7PiA47BUXBuqMdxkpyrUQvE',
    appId: '1:1018122395869:ios:54fca69309360a547d3b34',
    messagingSenderId: '1018122395869',
    projectId: 'meditechapp-86337',
    storageBucket: 'meditechapp-86337.firebasestorage.app',
    iosBundleId: 'com.example.meditech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1iumzSOtRXvXvfoNIlcJqHtcHZe77SeY',
    appId: '1:1018122395869:web:6effd89ed576dc587d3b34',
    messagingSenderId: '1018122395869',
    projectId: 'meditechapp-86337',
    authDomain: 'meditechapp-86337.firebaseapp.com',
    storageBucket: 'meditechapp-86337.firebasestorage.app',
    measurementId: 'G-D1CHMBZVV5',
  );
}
